sonar.projectKey=Axel-tasklist-backend
sonar.projectName=Tasklist Backend
sonar.sources=src
sonar.exclusions=src/__tests__/**
sonar.tests=src/__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
